backend:
  name: git-gateway
  # This tells the site to use the Identity service you just turned on
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "announcements"
    label: "School Announcements"
    folder: "announcements"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Headline", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Message Content", name: "body", widget: "markdown"}
